### ISSUE TITLE
[Design/Dev Coordination] - Host_v2 Answer Selector Design in Short Answer Mode

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#1121]
# Issue: General #

Currently in `host_v2`, when a user clicks on one of our Victory Graphs, they are presented with a list of players that selected that answer. For example, with confidence you can see the list below the graph here:
![Screenshot 2024-06-28 at 17 27 49](https://github.com/rightoneducation/righton-app/assets/79417944/95e14433-93b9-4f75-842c-e62fda7784aa)
[Figma Link](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15172-169568&t=l8czDNNy5TxQm7tp-4)

This works fine in multiple choice but I am looking for guidance on this component when the game is in Short Answer Mode. In this situation, the full text answer is currently being shown and it blows up the formatting of the whole component. 

In other places in the design, we show similar, user-submitted long text in a different format:
![Screenshot 2024-06-28 at 17 31 14](https://github.com/rightoneducation/righton-app/assets/79417944/5f7b3db3-4ce8-4ba5-a688-a0c378742d0e)
[Figma Link](https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=15090-142731&t=l8czDNNy5TxQm7tp-4)

How should this component look when the game is in Short Answer Mode?

**Comment by OliviaKnestaut** [comment]
Hey Drew!
I just wrapped up the final mockups for the short answer mode confidence meter. This formatting is pulled directly from how the other bar graphs format typed responses. You may notice that "Confused Dan" at the bottom wrote an answer that went over one line, Oh no! But don't fear, that the answer is collapsed under the little caret symbol.
![image](https://github.com/rightoneducation/righton-app/assets/58820071/1e7d987a-7c8b-4c10-8b9a-2a7a2c367732)
Feel free to message me with any questions,
Olivia
