### ISSUE TITLE
[Central_v2] - Image Upload Modal - Dotted Border Coordination

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#1345]
Hey @rodhinn-righton, are we married to this exact dotted border on the image upload modal?

<img src="https://github.com/user-attachments/assets/74841eb0-c307-499f-bf9b-be540bb58144" width="450" height="324" />

It's weirdly complicated to get this thing working exactly as it's described here. Notably, ensuring that there is consistent padding around the frame (shown here as 25px). Currently, given the technical complexity, the closest I've been able to get is to have a 5% padding based on width and height. So if the image upload is a rectangle, the padding will differ in height and width: 

Here's how it looks:

https://github.com/user-attachments/assets/2b7994c4-62a6-4a35-8c42-be2ea3f6c552

Personally, I think this looks a bit janky (differing border padding and the way that the grey drag/drop box doesn't infill perfectly around the border). Are we committed to this or do you have any ideas on alternatives to this?

**Comment by rod-hinn** [comment]
Yeah, it's ugly. Let me design something. I'm gonna move it into design.

**Comment by rod-hinn** [comment]
Final decision - go with this on all breakpoints -(1px as shown on Storyboard) 

![Image](https://github.com/user-attachments/assets/4c2318d3-0854-43ed-b9c3-40a0275e9a13)

**Comment by drewjhart** [comment]
This has been integrated into the latest create question flow
