### ISSUE TITLE
[Central_v2] - Create Question Flow - Mini-QA

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#1368]
This issue captures the QA process for the Create Question Flow. This process can be conducted via the following link: https://dev-central.rightoneducation.com/create/question. This process is intended to test the functionality of the core create question flow and will include issues like responsiveness to varying device sizes, animations, and error states. However, there are still some aspects of the flow that are not complete, so it we are not aiming for a 100% complete test. 

Here is what is to be include in the test:
- Image upload (Upload, drag and drop, URL)
- CCSS select via mouse and via keyboard
- Title change
- Correct highlighting of cards based on which stage the user is at
- Opacity change when card is complete, opacity change when completed card is clicked
- Correct answer card text updates
- Additional correct answer card fields added
- Incorrect answer card animations, incorrect answer card edits
- Refreshing the page should retain all previously completed fields. Pressing the discard button should clear the cache so that that that information is deleted
- Pressing the save button when fields are incomplete should display error states highlighting incomplete fields. Upon first edit to those fields, error states should disappear
- All of the above cases should work in mobile, tablet and desktop views.

Here is what is not to be included in the test:
- AI integration (this feature is currently being implemented by the dev team)
- Save button functionality when all fields are complete (this will cause the "Saving Question" modal to error as you don't have authorization

Additionally, please note that the components and behaviour are implemented per the in-depth designs and annotations on Figma:

https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=21108-644264&t=DuGTRgFpLedMt3FL-4

Finally, for further information on the kinds of tests that can be done here, you can review the dev team's testing at this document:

https://docs.google.com/spreadsheets/d/1n6-Q7BY6xVckA2GLux70b0SvvXBqjP0RGpYPKHqvZHM/edit?gid=0#gid=0

Much appreciate the feedback on this. The goal here is to confirm that the product is meeting the Figma and that the implementation is hitting the quality that's expect. Thanks again!

**Comment by drewjhart** [comment]
To log bugs that are uncovered, you can create an issue and assign myself to it. I'll then push it through the Kanban. You can use this template issue as a means a basis for the github issues you are creating:

https://github.com/rightoneducation/righton-app/issues/1369

**Comment by drewjhart** [comment]
In an ideal world, with infinite time we would conduct the following:

Desktop:
- PC - Chrome, Edge, Firefox
- macOS - Chrome, Safari 

Tablet:
- Android
- iOS

Mobile:
- Android
- iOS

I think given this is an interim QA session on a limited flow though, we can try for the abridged version here:

Desktop:
- PC - Chrome, Edge (optional)
- macOS - Safari 

Tablet:
- Use devtools in Chrome to simulate Tablet size by selecting iPad Mini or iPad pro from available devices, like so:
Go to: "View, Developer, View Developer Tools"
![Screenshot 2024-12-03 at 13 27 18](https://github.com/user-attachments/assets/bd2dbe39-d39a-404c-bec9-09dea797e340)

Mobile:
- Use devtools in Chrome to simulate Mobile size by selecting iPhone XR from available devices, like so:
![Screenshot 2024-12-03 at 13 27 31](https://github.com/user-attachments/assets/ce7b3931-62a5-4f18-b9ae-9d6230c6b06a)

- Additionally, if someone could test swiping, gestures, and scrolling feel on an actual device (android or mobile), that would be super useful as well.

**Comment by rod-hinn** [comment]
Closing this as this is finished -- just saw the last note and we did test swiping gestures on both mobile and iPad and did not note any bugs.
