### ISSUE TITLE
[Central_v2] - Bug Report - # 6 Mobile

### ISSUE THREAD

**Issue by jennyoonn** [rightoneducation/righton-app#1374]
**Describe the bug**
Cards don't highlight on click, instead the highlight happens in order of question card -> correct answer -> incorrect answer. 

**To Reproduce**
1. Go to the create question page.
2. Observe how the question card is already pre-selected. 
3. If I don't finish filling out everything in the question card and move on the the answer card, on click the highlight does not appear. 

**Expected behavior**
Cards should highlight on click. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : Chrome

**Smartphone (please complete the following information):**
 - Device: iphone 14 pro
 - OS: iOS18.1.1

**Additional context**

**Comment by drewjhart** [comment]
Hi @jennyoonn, do we know if the highlight should change on click? Like it makes sense to me but I can't find anything with that functionality in the Figma or Olivia's Loom video. Here are the links:

https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=21108-644264&t=BtUNR4OMBcynJBlm-4

https://www.loom.com/share/2ebbed30376d4c1db595a0399f98bd82?sid=49261443-ba6c-4307-a4a2-a4e2e29f6ec2

**Comment by rod-hinn** [comment]
To contextualize and reaffirm, we discussed this in meeting (with Chelsea). Cards highlight the expected step, not the click. So, what you have is correct. Closing.
