### ISSUE TITLE
[Central_v2] - Bug Report - # Lines 20, 37, 53 Desktop

### ISSUE THREAD

**Issue by chelcha** [rightoneducation/righton-app#1377]
**Describe the bug**
Discarding the data returns UI to homepage

**To Reproduce**
1. Go to Create Question page
2. Click on 'Discard'

**Expected behavior**
Discarding clears page but remains on Create Question

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Chrome; Safari

**Additional context**
Note** confirmation before discard should be implemented

**Comment by drewjhart** [comment]
Closing this in favour of a github issue for Discard Question modal to resolve gap in Figma per our discussion earlier today. This can be found here: https://github.com/rightoneducation/righton-app/issues/1395
