### ISSUE TITLE
[Central_v2] - Bug Report - #10 Mobile

### ISSUE THREAD

**Issue by jennyoonn** [rightoneducation/righton-app#1378]
**Describe the bug**
Change Image once an image is uploaded is not working as intended. When I upload an image, and I click on it to re upload, only the 'x' to leave the modal and save button are shown. I have to click on my existing image for the button to appear to prompt me to re-upload a new picture. 
**To Reproduce**
1. Go to create question
3. Click on upload image button and upload an image
4. Save your image
5. Click on your image again
6. Click on upload image
7. Observe there is no button to reupload
8. See Error

**Expected behavior**
The button to reupload should appear without having to click on your image on the modal. 
**Screenshots**
![IMG_785E5FE2A121-1](https://github.com/user-attachments/assets/c2969321-8e6c-4dcd-abd5-8a34a2a6ebb9)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone14 Pro
 - OS: iOS8.1.1

**Additional context**

**Comment by drewjhart** [comment]
Hi @jennyoonn, I think this is per Figma. Note the annotation here:

![Screenshot 2024-12-10 at 11 15 46](https://github.com/user-attachments/assets/133dbdbc-fbc3-4de7-8719-af06b81a8be8)

https://www.figma.com/design/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=23157-44470&t=BtUNR4OMBcynJBlm-4

Let me know if I'm off base though! 

cc @rod-hinn

**Comment by rod-hinn** [comment]
In design system.
