### ISSUE TITLE
[Central_v2] - Bug Report - # Line 9

### ISSUE THREAD

**Issue by chelcha** [rightoneducation/righton-app#1383]
**Describe the bug**
On Safari, save button doesn't work after image uploaded via URL

**To Reproduce**
1. On Safari, go to Creation Question page
2. Click on image URL in create question card
3. Paste URL
4. Click save
5. See error

**Expected behavior**
The save button to save the uploaded image

**Screenshots**
<img width="947" alt="Screenshot 2024-12-05 at 19 13 11" src="https://github.com/user-attachments/assets/223d6ab8-24a0-4bf4-b54d-d265ac5e6ae7">
<img width="732" alt="Screenshot 2024-12-05 at 19 13 43" src="https://github.com/user-attachments/assets/51432214-b4f7-484b-8b01-695042870c66">

**Desktop (please complete the following information):**
 - MacOS
 - Safari

**Additional context**

**Comment by drewjhart** [comment]
fixed!
