### ISSUE TITLE
[Central_v2] - Bug Report - # 20 Mobile

### ISSUE THREAD

**Issue by jennyoonn** [rightoneducation/righton-app#1384]
**Describe the bug**
Discard clears the data but also kicks the user back to the homepage. 
**To Reproduce**
1. Create game
2. Fill out information in the question game creation cards
3. Click Discard
4. See error (you are brought back to the homepage)

**Expected behavior**
When clicking the Discard button, we would expect all the information to clear but stay on the create game page. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari

**Smartphone (please complete the following information):**
 - Device: iPhone14 Pro
 - OS: iOS8.1.1

**Additional context**

**Comment by drewjhart** [comment]
Same issue as: https://github.com/rightoneducation/righton-app/issues/1377

Closing per discussion from previous meeting in favour of: https://github.com/rightoneducation/righton-app/issues/1394

@rod-hinn
