### ISSUE TITLE
P4: Remove text in top left of RightOn Central

### ISSUE THREAD

**Issue by autistic-dragon** [rightoneducation/righton-app#168]
![image](https://user-images.githubusercontent.com/30423050/149975568-35f12c88-43a0-4f2f-bff4-491f51035551.png)

The text in the top left (in this case, Teacher/ExploreChromebook) was intended only to be a label on the mockups and not supposed to be displayed in the actual website.

**Comment by NeuveltP** [comment]
Two other adjustments to make to the top bar. For the Explore tab, the actual "Explore" text should move a few pixels to the right of the explore icon to even out the spacing, and the Explore tab should switch to the same shade of grey as the Game Maker tab when it is deselected. At the moment it stays white regardless of if it is selected or not.
