### ISSUE TITLE
P1: Search Bar doesn't include text found in descriptions, only titles

### ISSUE THREAD

**Issue by NotMakoto** [rightoneducation/righton-app#172]
Synopsis:
When using the search functionality to find games to look for, you can only get results linked to the title of a game. If searching for a game by what's in the description, they do not appear. Here is a link to the use case regarding filtering and search options if needed: https://docs.google.com/document/d/16grHrYM02DiSLtj2FjjDpLDpdWntnvwvRz8XiTmioe4/edit#heading=h.euz2w4i5qjdf 

Steps to Reproduce:
1. Search for a game based on what's inside of the description.
2. Notice how nothing will appear after typing in words found in the game's description. 
- 2.5. For further check, search for the game using the game's name to verify that games can be searched by title alone as of now.

Visuals: (Note: The game in question for the visuals will be "Fun Facts about Food".)
![image](https://user-images.githubusercontent.com/90802950/150020846-339d68b4-880b-4e5c-800f-823bc9ee4604.png)

1. ![image](https://user-images.githubusercontent.com/90802950/150020887-1863fdff-b79a-4cfd-8e5a-ff252f735a4e.png)
2. ![image](https://user-images.githubusercontent.com/90802950/150020972-892ec9d3-6615-4786-8a13-539ff8acba0a.png)

**Comment by ankittrehan2000** [comment]
Hey this issue was fixed in a new version of the app, here is a new issue that you could help with if interested: https://github.com/rightoneducation/righton-app/issues/225
