### ISSUE TITLE
P4: Update image thumbnails to new placeholder

### ISSUE THREAD

**Issue by NeuveltP** [rightoneducation/righton-app#177]
The UX Team has created new placeholder images for game thumbnails, these should replace the current generic thumbnails.

Current: 
<img width="521" alt="Screen Shot 2022-01-20 at 4 50 15 PM" src="https://user-images.githubusercontent.com/81721520/150427822-9b13aa30-eb1b-4e2c-8e6e-7ac37eeb331a.png">

New:
<img width="553" alt="Screen Shot 2022-01-20 at 4 50 05 PM" src="https://user-images.githubusercontent.com/81721520/150427840-131f77ae-9c15-4437-bffd-f8cd66c9e4f0.png">

**Comment by zach2025** [comment]
Fixed in Question Detail changes (A Pull request for these changes was not created as they were accidentally pushed directly from my local branch to the sprint1-branch directly. Information about these changes can be found in Issue #155)
