### ISSUE TITLE
P2: Junk text in CCSS label on game tabs (Repeat of #188)

### ISSUE THREAD

**Issue by NeuveltP** [rightoneducation/righton-app#182]
A few games have junk text as a ccss label

<img width="544" alt="Screen Shot 2022-02-01 at 1 34 08 PM" src="https://user-images.githubusercontent.com/81721520/152029660-73b5e31c-198d-4fda-887c-9edb1fee4cf8.png">

**Comment by zach2025** [comment]
This is data from testing the resolvers. Once we near the completion of the MVP and reset the data to only be the usable games, this will no longer be an issue
