### ISSUE TITLE
Several games still have issues with displaying their CCSS info on RightOn Central

### ISSUE THREAD

**Issue by autistic-dragon** [rightoneducation/righton-app#188]
![image](https://user-images.githubusercontent.com/30423050/153932425-4d370281-bc6c-4142-8808-967aa8cd01d9.png)

This is an issue I'm seeing mostly with older games. Changing the CCSS seems to fix this issue though.

![image](https://user-images.githubusercontent.com/30423050/153932676-93669438-effc-43db-9ce2-33b47ccecd0d.png)

**Comment by zach2025** [comment]
Same Issue and Explanation as #182: This is data from testing the resolvers. Once we near the completion of the MVP and reset the data to only be the usable games, this will no longer be an issue
