### ISSUE TITLE
Creating a new question does not cause the question to immediately appear after going back to the game view

### ISSUE THREAD

**Issue by autistic-dragon** [rightoneducation/righton-app#189]
![image](https://user-images.githubusercontent.com/30423050/153932936-0dd8f39a-a84d-4c2a-9ca1-89c11baa7b97.png)
After creating a question and clicking "save", the game is still empty. After refreshing the page, the question appears. It would probably be a smoother experience if the question appeared right after it was created.
![image](https://user-images.githubusercontent.com/30423050/153933049-e29f2b7f-6829-4fd2-aef1-ba112dfaa812.png)

**Comment by yurichen17** [comment]
Is this still an issue? I'd love to be assigned to this!
