### ISSUE TITLE
RightOn Host: Create view general game screen and pair display code screen

### ISSUE THREAD

**Issue by EricNguyen-B** [rightoneducation/righton-app#204]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/53154237/155929166-32fe535f-7a22-4026-a74d-e3fc835aae77.png">

**Comment by EricNguyen-B** [comment]
You wouldn't need to worry about the Pair Code Screen just yet. I would recommend to focus on the left screen (Start Game Screen) first

**Comment by lucahendicott** [comment]
This is sort of my pseudo code and thought process for this screen so far based off of the page design and the example data Ankit has provided so far.

 //GameCode
    //game.gameCode -- get current game by id

      //CurrentGame
      //game.id or just id?
      //we want to display game title and how many questions

        //GameMode
        //game.isAdvanced -- determine which mode if false then we go on to continue with basic mode functionality
        
      //StudentsInSessionCount
      //teams.teamMembers.id? map this array to fetch and return count, render count to screen

        //CurrentStudents
        //teams.teamMembers.id? map to fetch and return team member names and attributes? as buttons with functionality to remove(delete) individual members
        //when a team member is in the session do we also need to be storing their answers at this stage?

    //StartGameButton
    //triggers next screen -- teacher / answer dashboard with time and first question

**Outstanding clarifying questions I have for implementation:**
-Do we need to get routing/ all updates from sprint 1/2 merged into sprint3-branch?
-How DO we get to this page? After launch game is selected from central?
-how is routing going to work here? 
-do we render this page/ component in app.jsx?
-How should file structure look with these pages/  components? Is this all in one component/ file or multiple sub components separated out?

I'll definitely have more functionality questions once I've dove further into the thick of it!
