### ISSUE TITLE
RightOn Host: Create game in progress game screen

### ISSUE THREAD

**Issue by EricNguyen-B** [rightoneducation/righton-app#205]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/53154237/155929297-5cd451b2-a088-4b01-b37f-cbd233a6237b.png">

<img width="212" alt="image" src="https://user-images.githubusercontent.com/53154237/155929333-083a1e34-52db-438e-bc2c-44381434a4a6.png">

<img width="167" alt="image" src="https://user-images.githubusercontent.com/53154237/155929359-c325b294-ae26-4638-adf2-f29b30b26e80.png">

**Comment by zach2025** [comment]
**Route:** host.righton.com/game/:gameId/question/:questionIndex/:phase
:gameId = the id of the game being played
:questionIndex = the index of the question being played
:phase = 1, 1/results, 2, 2/results

**Data**
```
props = {
    gameId: '1234',
    questionIndex: 0,
    phase: {
        phase: '1',
        time: 180,
    }
    question: {
        id : '1389',
        text : "How many total squares (of any size) are there on a checkerboard?",
        imageUrl: 'https://media.istockphoto.com/photos/wooden-chess-board-picture-id476469645?s=612x612',
        answer: '204 squares',
        instructions: 'To get this answer, you not only need to count all of the 1x1 squares, but you need to consider the 2x2, 3x3, 4x4, etc. all the way up to the full 8x8 square. Counting every one of those squares together will return a sum of 204 total squares.',
        wrongAnswers: [
            { choice : '100 squares', explanations : 'Wrong choice explanation 1' },
            { choice : '300 squares', explanations : 'Wrong choice explanation 2' },
            { choice : '800 squares', explanations : 'Wrong choice explanation 3' }
        ]
    },
    totalPopulation: 24

This would be real-time data that is constantly being changed/updated through API calls. This info may come through imported API calls that are either passed down through props or directly imported into the file, so this information may change places but is ultimately still needed on the page.
    totalAnswered: 12
    peopleChoices: {
        A: 1,
        B: 12,
        C: 8,
        D: 3,
    }
}
```

**Components**
[Answer Dashboard _ Answer 13-2.pdf](https://github.com/rightoneducation/righton-app/files/8236366/Answer.Dashboard._.Answer.13-2.pdf)

**Comment by EricNguyen-B** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/53154237/166585846-ca68af70-d42f-487d-a3fc-6b4c05df837c.png">

<img width="478" alt="image" src="https://user-images.githubusercontent.com/53154237/166585864-f53049b1-ecd1-4009-9d6d-c56d52c04999.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/53154237/166585962-5760bb25-46c8-40a6-a6b9-fcb50e1b57a3.png">

<img width="455" alt="image" src="https://user-images.githubusercontent.com/53154237/166586002-923eefcf-4746-4fa9-83f9-8f742dabc527.png">
