### ISSUE TITLE
RightOn Display: Create RightOn Display initial screen

### ISSUE THREAD

**Issue by EricNguyen-B** [rightoneducation/righton-app#208]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/53154237/156625914-094bcb7a-740e-4721-b4e3-7d5dc88a8095.png">

**Comment by JJackson914** [comment]
**Route:** display.righton.com/gameID/gameCode
gameID: ID of the game being played
gameCode: code of the game being hosted

**Data:**
`
props = {
    game: {
        id: "123abc",
        title: "Practicing Percents: Let's Go Shopping!",
        code: "9349",
        cluster: "A",
        domain: "RP",
        grade: "7",
        standard: "3",
    },
    studentsInSession: "28",

    gameID, gameTitle, gameCode should stay static, while studentsInSession should be updated.
}
`

**Components:**
[DisplayScreen.pdf](https://github.com/rightoneducation/righton-app/files/8247290/DisplayScreen.pdf)

(File names here might not reflect final file names)
Black Box = DisplayLaunchScreen.jsx
Yellow Box = DisplayImage.jsx
Dark Green Box = DisplaySwitchMode.jsx
Red Box = DisplayGameInfo.jsx
Blue Box = DisplayGameCode.jsx
Pink Box = DisplayStudentTotal.jsx
Light Green Box = DisplayStartGame.jsx
