### ISSUE TITLE
RightOn Display: Create RightOn Pair code screen

### ISSUE THREAD

**Issue by EricNguyen-B** [rightoneducation/righton-app#209]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/53154237/156626109-411c7fe7-91af-4a1c-9a07-23d057dd391f.png">

The QR code is not needed for the MVP

**Comment by drewjhart** [comment]
**Route:** 
display.righton.com/gameID/gameCode/pair
gameID: ID of game
gameCode: code of game for pairing

` 
props = {
"game":{
     "id":"1234abcdef",
     "gameCode":1234,`
}}

![paircode](https://user-images.githubusercontent.com/79417944/158297040-f367ec8f-d94e-4b23-9844-e60deca1fcbc.jpg)

Yellow: Container 
Orange: Back button to Jared's display.righton.com/gameID/gameCode
Green: Nested Grid container/items for images/text
Purple: Card with collapse for reveal/ grid container for qr code and text field (separate components)
Pink: start button

Questions:
- How to generate QR code (Ryan flipped me: npmjs.com/package/react-qr-code)
- Responsive grid layouts
