### ISSUE TITLE
P3: Clicking anywhere outside of the expanded sort menu dropdown should close the dropdown

### ISSUE THREAD

**Issue by NeuveltP** [rightoneducation/righton-app#217]
At the moment, the only way to close the sort menu is to click on the Sort By tab again. It would be a minor UX improvement to allow for the dropdown to close by clicking anywhere outside of it.

**Comment by lucahendicott** [comment]
That's a great point! I'd definitely recommend for the users sake to have an “x” or “close” button on that drop down along with the ability to close by clicking outside of it. If central was ever being used on different devices in the future, sometimes certain viewports can make it difficult to click outside of a menu. Ie: the menu could take up a lot of the screen on a small screen
