### ISSUE TITLE
Postman research

### ISSUE THREAD

**Issue by lucahendicott** [rightoneducation/righton-app#228]

**Comment by lucahendicott** [comment]
Here's the video @maniramezan sent for a beginners guide!
[Postman Tutorial](https://www.youtube.com/watch?v=FjgYtQK_zLE)

Highly recommend getting postman downloaded if you haven't already! I'll drop the link here:
[Postman Download](https://www.postman.com/downloads/)

In addition to/ alternatively to any solo studying - @drewjhart and I are going to meet tomorrow (Friday 5/13) @ 2pm ET for a postman study session. I've got a decent, very basic understanding of testing endpoints with Postman. I'll be doing a demo of some requests I've previously made in an environment for a past project in postman. @EricNguyen-B , @zach2025  - Please feel free to join if you're available! Let us know on Slack if you're interested and I'll send you our google meet link.

**Comment by drewjhart** [comment]
That tutorial is great. He's also done an [update ](https://www.youtube.com/watch?v=JzpFsrZnNDol) which is pretty good too. Thanks for the overview on Friday - helped a bunch!
