### ISSUE TITLE
"Don't Get Tricked" screen shows Hints card

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#32]
### Observed
"Don't Get Tricked" screen shows the Hints card
Screenshot on iPhone X:
![IMG_C4A699909493-1](https://user-images.githubusercontent.com/1576365/87449329-a3ace100-c62f-11ea-8ea3-2891706e2410.jpeg)

### Expected
"Don't Get Tricked" screen doesn't show the Hints card, only Question and Choose One cards.

**Comment by amarax** [comment]
I think the build is #29

**Comment by maniramezan** [comment]
Actually https://github.com/rightoneducation/righton-app/pull/36 PR
