### ISSUE TITLE
Trick answers, once added, should be read-only and have a larger clickable area for Facilitators

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#33]
In the July 14 build:
When a trickster team is entering trick answers: once a trick answer is added to the list of trick answers, it:
1. Should be read-only (i.e., not editable or deletable)
2. Have a larger clickable area (e.g., the entire button)

Please also apply this update to the "Don't Get Tricked" / voting screens where student teams try to vote for the correct answer (and try not to be tricked by the trickster team's trick answers).

**Comment by sincwu** [comment]
Cool, based on testing that Yong Lin and I did during our team sync earlier today:
- Trick answers, once added, are read-only and have a larger clickable area -- nice!
- When 4 or more trick answers have been entered: the time between clicking a trick answer and having it appear selected (if it was originally _not_ selected) or deselected (if it was originally selected) is 0.5-1 second -- this might not sound like a lot of the time, but the delay is long enough that it might be confusing to users (wondering if their click was properly registered). If it'd be possible to make this click-to-select/deselect virtually instantaneous (or faster than it currently displays), that'd be great.

**Comment by sincwu** [comment]
In the Sep 28 build (Version 1.0 (1)), this issue seems to have returned (at least on Android Galaxy S7). Steps to reproduce:
1. Enter 1 or more trick answers
2. Click into any of the trick answer fields: note that a cursor appears, and one can is able to edit (and even completely delete) the trick answer. Trick answers, once added, should be read-only.

**Comment by maniramezan** [comment]
@sincwu Hmm, that was intentional, probably my bad understanding of the new design that we're letting the user to modify his past entered answers. If not, can fix it quickly

**Comment by sincwu** [comment]
Cool -- that's great that you can make the change quickly. Yeah, in alpha pilots, we found that sometimes students would change other students' trick answers (both accidentally and intentionally). This also opened technical complexities -- e.g., when multiple students were trying to edit/save the same field. As such, we decided that it might be better to make the trick answers read-only. If a student would like to change an answer, one can simply enter a new trick answer, which is then added to the shared list seen by all devices.

**Comment by sincwu** [comment]
Incidentally, I just added a clarification to the title for this issue: the requested larger clickable area applies specifically to the Facilitator role -- i.e.:
- Only the Facilitator can select/unselect trick answers (please note that even after a team has entered one trick answer, the Facilitator can select/unselect it)
- In the current release, to select/unselect a trick answer, the Facilitator has to click quite precisely on the checkmark (in the circle on the right side of the trick answer). As the trick answers are read-only, we can enable the entire button to be clickable by the Facilitator to select/unselect it -- thanks!

**Comment by maniramezan** [comment]
Implemented and pushed to appcenter as part of https://github.com/rightoneducation/righton-app/pull/39. This should be fixed in the latest app version and js bundle.

**Comment by sincwu** [comment]
Looking good! Validated and closing this issue.
