### ISSUE TITLE
RightOn Host: Create New Screens

### ISSUE THREAD

**Issue by lucahendicott** [rightoneducation/righton-app#337]
Build out the UI for these 3 new screens that were added to the RightOn Host flow. 

![Image](https://user-images.githubusercontent.com/70814349/190248405-a0623719-292b-401f-81de-16ad936929be.png)

![Image](https://user-images.githubusercontent.com/70814349/190248424-a58a7b76-42e0-41af-81ad-bd51fcbc65ea.png)

**Comment by drewjhart** [comment]
2022-09-17: UI done, need to know about states to properly hook them up
