### ISSUE TITLE
RightOn Mobile UI: Phase 1 Nice Try/ Correct Displays

### ISSUE THREAD

**Issue by lucahendicott** [rightoneducation/righton-app#382]
ToDo:

- [x] Update headers - spacing and size
- [x] Add question image and question text to the card body (see updated figma screenshot below)
- [x] Test a question with something in the `instructions` field to see if they parse out properly
- [x] Handle UI for questions with no instructions in that field - maybe remove instructions card entirely if there aren't any?

[Source Code](https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=7557%3A221842)

![Image](https://user-images.githubusercontent.com/70814349/199339032-2d7a6dda-6690-42ca-b529-7d27a4d1cecf.png)

**Comment by ryanabooth** [comment]
https://github.com/rightoneducation/righton-app/pull/418
