### ISSUE TITLE
RightOn Mobile UI: Phase 2 Wrong Answer Info Carousel

### ISSUE THREAD

**Issue by lucahendicott** [rightoneducation/righton-app#383]
Currently the wrong answer explanations are separated in individual cards with proper titles, but need to get them separated to be "swipable" left and right. Each one needs to fill the the screen individually 

Seems like a Carousel indexing issue perhaps?

- [Phase 2 Source code](https://github.com/rightoneducation/righton-app/tree/dev/mobile/src/Student/screens/Game/PhaseTwoBasicGamePlay)
- [Component rendering the carousel Component](https://github.com/rightoneducation/righton-app/tree/dev/mobile/src/Student/components/HorizontalPageView)

![Image](https://user-images.githubusercontent.com/70814349/198133133-0af58fb7-3a8a-4fd4-8787-8a46da5c9ea7.png)

**Comment by ryanabooth** [comment]
https://github.com/rightoneducation/righton-app/pull/407
