### ISSUE TITLE
After trick answers have been entered, trim any leading or trailing spaces

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#42]

**Comment by maniramezan** [comment]
Lets do this as part of https://github.com/rightoneducation/righton-app/issues/43 since it's kinda a simple version of input validation work that we need to design and implement in client.

**Comment by sincwu** [comment]
Following up with our 10/20 chat: here's a draft wiki with global input validation requirements:
https://github.com/rightoneducation/righton-app/wiki/Trick-Answer-Input-Validation
