### ISSUE TITLE
[Host] [Mobile] Wrong Answer Explanations should preserve line breaks and white space

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#423]
When displaying Wrong Answer Explanations across both Host and Student screens, currently line breaks and white spaces appear to be ignored (default behaviour of HTML pages). 

**Host screen**
<img width="293" src="https://user-images.githubusercontent.com/1576365/203236754-f4e04617-c536-4ddd-af11-232ea497a4b5.png">
Link to screenshot in flow: https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11984%3A375580&t=xLZLDag9kiD7fKfh-4

**Student screen**
(Screenshot to be updated with clearer content to display bug)
Link to screenshot in flow: https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11960%3A378233&t=xLZLDag9kiD7fKfh-4

Ideally, line breaks and white spaces should be preserved as teachers who enter questions will commonly use them to improve readability of large blocks of explanations.

**Comment by amarax** [comment]
@sincwu when we last discussed this, we had assumed that the example in the screenshot had line breaks already. This is apparently not true: the question featured doesn't have any line breaks!

**Comment by sincwu** [comment]
Good catch, thanks! Will check out the wrong answer explanations and work with Marizza to add line breaks as appropriate.

**Comment by sincwu** [comment]
The question in this example is the one from Row 3 of the following [Google Sheet](https://docs.google.com/spreadsheets/d/1eOHjA-OuT8h7GIauwKZYkF4DXYKR8S0bMTi2Llsua24/edit?usp=sharing). The question itself does not have any line breaks, but the wrong answer explanations do have line breaks that should be preserved. Thanks, all!
