### ISSUE TITLE
[Host] When displaying Wrong Answer Explanations, correct answer still has the label "Wrong Answer Explanation"

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#426]
Currently, the correct answer accordion still displays the label "Wrong Answer Explanation". In the screenshot below, `B. 51` is the correct answer.

<img width="293" src="https://user-images.githubusercontent.com/1576365/203236754-f4e04617-c536-4ddd-af11-232ea497a4b5.png">

Link to screenshot in flow: https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11984%3A375580&t=xLZLDag9kiD7fKfh-4

Proposed fix: "Wrong Answer Explanation" is just replaced with "Correct Answer", with no changes to existing behaviour.

**Comment by drewjhart** [comment]
Weirdly enough, this was an issue in the game data on the `backend` (that I had entered in). Answer B wasn't set to "true" answer so it was reading as a wrong answer by `host` . I didn't see this issue in any of the other games but let me know what you see. I'm closing this for now.

Here's the fix:


![Image](https://user-images.githubusercontent.com/79417944/203493007-c29867b2-63ea-4a9c-bd46-156a80580cb3.png)
