### ISSUE TITLE
Treat numbers, whether entered with commas or not, as equivalent

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#43]
When a user enters 1) a guess at the correct answer before the correct answer has been revealed or 2) a trick answer after the correct answer has been revealed: treat numbers, whether entered with commas or not, as equivalent.

For example, in the scenario below, "1080" is the correct answer. However, when "1,080" is entered before the correct answer has been revealed, "1,080" is identified as a wrong answer and added to the trick answer list. When "1,080" is entered after the correct answer has been entered/revealed, "1,080" is accepted as a trick answer even though it is equivalent to the correct answer.

This issue tracks just the handling of commas. In the future, we may want to think about handling other equivalences -- e.g., 2/4 = 1/2 = 0.5.

![image](https://user-images.githubusercontent.com/8507656/94511530-77d0de80-01ce-11eb-99de-0ab82c315f2f.png)

**Comment by maniramezan** [comment]
I think this requires a deeper dive into how the answers should be formatted. Like being able to tag questions and restrict the answers to: `Numeric`, `Alphanumeric`, or free form or something similar so client can uses those logics to prevent invalid inputs. Like if the answer is only natural numbers, no need to add comma vs. fractional numbers that can have dot in them. I'll mark this as enhancement and design for now.
