### ISSUE TITLE
Screenshots showing student views can be confusing for teachers

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#437]
When displaying screenshots to show what the current student views are, teachers may be confused when the screenshot doesn't show the actual answers or scores, because it isn't clear that the screenshots are not updated live.

Specifically, these screens are affected (links to screenshots):
- Phase 1 Results https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A375163&t=WXX0Fd9sLgRUh712-4
- Phase 2 Results https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A375165&t=WXX0Fd9sLgRUh712-4

To address this, Figma assets have been updated to include a "Sample Screen" banner to indicate that it is just a static sample. Updated assets are available for export:
- SVP1Results https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A380114&t=WXX0Fd9sLgRUh712-4
- SVP2 Results https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A380732&t=WXX0Fd9sLgRUh712-4
- SVP2Start (optional) https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A380743&t=WXX0Fd9sLgRUh712-4

**Comment by drewjhart** [comment]
sick, thanks. I'll add this in this weekend
