### ISSUE TITLE
[General] Figma Review

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#444]

**Comment by amarax** [comment]
@drewjhart if you could share a bit more context on the review, I can update the Figma file to suit the purposes of the review (e.g. update screenshots), I should have some time this week to do so if it suits the timeline!

**Comment by drewjhart** [comment]
hey! I don't think we'll need much on the Figma side for this item. This is basically a task to go through the apps and compare it to the existing Figma to ensure we are matching each of the screens. So no updates needed on your end! Thanks though!

**Comment by drewjhart** [comment]
Done with comments on  https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11957%3A373842&t=SGeD0ipYgjvbSbpc-0
