### ISSUE TITLE
[Mobile] On the Enter Your Name screen: when either First Name or Last Name is left blank, the app crashes (Android)

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#446]
The app crashes consistently during any of the following scenarios:
- First Name is left blank
- Last Name is left blank
- Both First Name and Last Name are left blank

Hi Yong Lin: Am first assigning this issue to you to suggest an error message/screen. Adding Drew as an fyi for now; please reassign as appropriate when ready for dev implementation.

**Comment by amarax** [comment]
I'll draw up the screens by today, and I would like to ask if the following are easy to implement:
- **most ideal** the app saves the name from previous entry so the student doesn't have to enter the name again when entering subsequent games
- button changes disabled/enabled state based on the text entry
  - ideally this happens in a way where when both fields are already filled and still in keyboard, the user can press "enter" on they keyboard, and the button enabled state changes to reflect this

**Comment by drewjhart** [comment]
Agree on your prioritizing here, @amarax, but I believe the saving of the name will require `localstorage` which we will need to tackle in the future. A button change is totally doable as a stopgap in the meantime though.

**Comment by amarax** [comment]
@drewjhart no worries, let's just drop that part of the design. I've put together a quick flow that I believe should be easy to implement https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12118%3A380115&t=WPHFU5tuxdg5m1H8-4

<img width="734" alt="image" src="https://user-images.githubusercontent.com/1576365/205870693-e5366725-8dbb-4d26-8fd4-5fedcb7bc18c.png">
