### ISSUE TITLE
[Mobile] On Wrong Answer Explanation screens, the wrong answer should be displayed in a separate line with its corresponding answer choice

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#456]
For example, in the below screenshot, "Wrong Answer Info 27" appears all in one line:
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11960%3A378233&t=b0vlf40o91SpwDSW-4

What should be displayed instead is:
Wrong Answer Info

          X. 27  

[where X is the corresponding letter for the answer choice]

Please see S.1.9 screens for reference:
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=7557%3A222329&t=b0vlf40o91SpwDSW-4

**Comment by drewjhart** [comment]
Hi @josephinaim, I'm assigning this to you as another UI item to get to whenever you've made it through your existing list. Let me know if you need any further information on this task.

**Comment by drewjhart** [comment]
Closing this out based on: https://github.com/rightoneducation/righton-app/pull/520
