### ISSUE TITLE
[Mobile] Alongside display of wrong answer explanations, also display correct answer explanation

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#462]
Teachers and students have noted that having this side-by-side comparison (e.g., by adding a card to the pre-existing card-swipe / carousel interface) would be helpful. Would be great to have some updated screens in Figma -- thanks, Yong Lin!

A couple additional notes:
- A few teachers have talked about not wanting to confuse their students with wrong answers / wrong answer explanations (e.g., in the case that students might inadvertently remember wrong answers as the right ones). Currently, wrong answer explanation screens are labeled: "Wrong Answer Info." It'd be great to continue to clearly distinguish the correct answer explanation from wrong answer explanations.
- It'd also be helpful if the letter associated with each answer choice (right or wrong) is clearly displayed. For example, in the draft prototypes (which already look pretty cool), it appears that the correct answer is answer choice C, though that may not be immediately clear. Look forward to seeing what you come up with next!

**Comment by amarax** [comment]
This design has been added to Figma and can be seen here https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12022%3A390347&t=MDWu1mCS8eypOEyR-4

<img src="https://user-images.githubusercontent.com/1576365/208042346-63c9831c-1618-4d91-b68a-8fc97806e569.png" width="500" />


A Figma prototype of this new design is available at https://www.figma.com/proto/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?page-id=7557%3A221842&node-id=12022%3A393843&viewport=7150%2C1187%2C0.34&scaling=scale-down&starting-point-node-id=12022%3A393843&show-proto-sidebar=1

**Comment by amarax** [comment]
From @sincwu 

> A few teachers have generally talked about not wanting to confuse their students with wrong answers / wrong answer explanations (e.g., in the case that students might inadvertently remember wrong answers as the right ones). In the sample designs: any ideas on how we might further or more clearly distinguish between correct and wrong answer explanations? (For example, the current wrong answer explanation screens are labeled: "Wrong Answer Info.")
> 
> One other quick thought: it might be helpful if the letter choice associated with the correct answer is also displayed. For example, in the prototypes, it appears that the correct answer is answer choice C, though that may not be clear.

**Comment by amarax** [comment]
Updated designs in Figma https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12185%3A381225&t=TWMKlUUwYk0nwrYP-4

Will need to review proposed updates to question screens. It may be possible to just implement changes for the Wrong Answer Explanation screens without changes to earlier ones, but will need to discuss this. Specifically:
- Will we need to show the player which answer they originally picked as the correct answer?

**Comment by amarax** [comment]
Updated screens in Figma after discussion with @sincwu.

For the question above, the answer for Beta v0.1 is NO, the player's previous choice in Phase 1 will not be shown for now.

Screens that were updated are:
- S.1.6 Answer the Question https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12396%3A387697&t=4kmldlhj91waQumL-4
- S.1.8 Pick the Trickiest https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12396%3A387698&t=4kmldlhj91waQumL-4
- S.1.9 Answer Explanations https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12396%3A388370&t=4kmldlhj91waQumL-4

These screens include an update to the option picking component. All states of this component can be found at https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12363%3A382671&t=4kmldlhj91waQumL-4

**Comment by sincwu** [comment]
Cool, thanks, Yong Lin -- nice work with all the details and tying everything together into a cohesive whole!
- Updates and clarifications re: the Submit Answer button states and how it changes to Answer Submitted (in Phase 1 & 2)
- Removal of the "Are you sure? modal
- Streamlined display of wrong answer explanations alongside the correct answer explanation

**Comment by amarax** [comment]
@sincwu I remember moving this issue to Done, but it seems to be in the Backlog again. 

If you moved it with the intention of starting dev work on it, could you remove the `design` label from it, clear the projected completion date, and unassign me from the task?

If you moved it to continue design work on it, could you clear the projected completion date, and add a quick comment (just "need to make design improvements" will do, no need for details yet)?

If you didn't move it, let me know and I'll shift it back to done 😆

**Comment by sincwu** [comment]
Good call, @amarax! At the end of our dev team meeting today, Josephina mentioned that, for a query that she had set up, it'd be helpful for her for the `done` tag to be removed (so that the issue appears in her backlog). We clearly have a Github process improvement opportunity here :) For now: good suggestion: I'll remove the `design` label, clear the projected completed date, and unassign you (your portion of the work here is done -- thanks!). In the future, we can either modify the steps in Github and/or, as I noticed Drew had done for a couple issues, create a UX issue and a corresponding dev implementation one. Thanks, everyone, for your patience and understanding -- let's add this to a list of process improvement ideas for 2023!
