### ISSUE TITLE
[Mobile] Validate player scores, particularly in Phase 2

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#478]
### Issue:
During the demo, it was noticed that some of the player scores weren't calculating accurately in Phase 2.

### Resolution:
TBD

**Comment by drewjhart** [comment]
Hi @Alexandra-Kushnirsky, if you run out of tasks, you can also dive into validating the player scoring (also something that might overlap with multiple questions). I think Phase 1 is easy (add ten points for a right answer) but phase two gets a little bit trickier, particularly with multiple players in a game. If you could do some testing on the scoring, particularly in Phase 2, that would be great

**Comment by sincwu** [comment]
Thanks, all, for diving into this further. Please note that that everything might be OK with the scoring (in both Phase 2 and in general) -- and this would be great to validate for a larger group of students. 
- During the 12/8 demo at Carver High School, there were >20 students, and we know a few of them crashed out
- Notably, several students, after 2 phases, had a score of 0, which would mean 1) in Phase 1, they chose an incorrect answer and 2) in Phase 2, their guess for the most popular / most likely chosen wrong answer had 0 votes (which is possible, though unlikely).
- Please refer to the screenshots below of the final leaderboard (on the Teacher Host side). 
![Host Leaderboard 1 of 2](https://user-images.githubusercontent.com/8507656/208824917-92a0fdab-1233-4fc6-bdd1-5b055507ddec.jpg)
![Host Leaderboard 2 of 2](https://user-images.githubusercontent.com/8507656/208824930-0c99c606-1033-4702-adbb-3599758c2529.jpg)

The scoring for Phase 2 can seem a bit complicated at first, but once you see it, it's pretty straightforward. 
For future details, please refer to S.1.10 in Figma: https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=10443%3A215357&t=FH8dJ2wtQreOAYgT-4
