### ISSUE TITLE
[Mobile] UI Updates on Monster Screen (S.1.3)

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#481]
### Issue:
UI updates to more closely match Figma

### Resolution:
Update relevant screen per comments on https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11957%3A373842&t=SGeD0ipYgjvbSbpc-0

**Comment by amarax** [comment]
@josephinaim I created a new branch with the updated assets to use for the Team Selection screen. https://github.com/rightoneducation/righton-app/compare/dev...481-mobile-ui-updates-on-monster-screen-s13

I've opted to export the assets in full and hope you can apply the rounded corners as part of the style. The details are included on the Asset Export page in Figma https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12387%3A385805&t=4kmldlhj91waQumL-4

If you would prefer the assets exported differently, please let me know and I can help to prepare them. Just @mention me here in a comment and I'll respond usually within a day, or you can ping me directly on Slack!

**Comment by josephinaim** [comment]
Thank you, I'll try it out!
