### ISSUE TITLE
[Mobile] P4: UI Updates for How-to-Play Onboarding Flow (S.1.4)

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#482]
### Issue:
UI updates to more closely match Figma

### Resolution:
Update relevant screen per comments on https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11957%3A373842&t=SGeD0ipYgjvbSbpc-0

**Comment by sincwu** [comment]
Following up with our 12/27 team meeting:
- Deprioritizing this to a P4
- Based on a solution idea tossed out by Alex (thanks!) to combine the app screen and "Phase 1 of X" sticker into one single image: I'll check in with Yong Lin during our next meeting on 1/3. In the meantime, we decided to place this issue on a backburner.

**Comment by amarax** [comment]
I would actually recommend to hold off on this task for now until the responsive behaviour is well-defined. There's a good chance the structure of the screen would need to change significantly.

Another suggestion would be to actually incorporate the "Phase 1" into the actual screen itself. From a UX perspective, it'd actually be useful for the players to know how many phases there are per question, and which phase they are at. Currently only the Host screens display this information.

**Comment by sincwu** [comment]
Wow, a week ahead of schedule you are, Yong Lin! As this item is a lower-priority one, I didn't tag you, but perhaps your Github ears were ringing. :) Agree with holding off on this task: great points on considering responsive behavior and, especially we support multiple questions per game, it might be helpful to let players know which phase of each question they're in.

**Comment by amarax** [comment]
@Alexandra-Kushnirsky I just committed the new asset for Phase 2, let me know if it works! https://github.com/rightoneducation/righton-app/commit/e2d3918dacb3fba794bbde26fa4f09ca936ab5df
