### ISSUE TITLE
[Mobile] UI Updates on Phase 1 - Wrong Answer Explanation and Results Pages (S.1.7)

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#485]
### Issue:
UI updates to more closely match Figma

### Resolution:
Update relevant screen per comments on https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11957%3A373842&t=SGeD0ipYgjvbSbpc-0

**Comment by drewjhart** [comment]
I've updated the screenshot and added further comments here:
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=11957%3A373842&t=beHYhT6sPnRzRepc-0



![Image](https://user-images.githubusercontent.com/79417944/211432404-d49766ed-4a47-44d8-9c55-21372aa485e5.png)



Let me know if anything is unclear or if you aren't seeing these issues on iOS

**Comment by drewjhart** [comment]
@josephinaim

**Comment by josephinaim** [comment]
PR #529 should take care of the UI issues with Wrong Answer Explanation (S.1.7), since the PR hasn't been merged yet, the changes aren't seen. I'm currently working on the spacing issue and the Phase 1 results stars on a new branch
