### ISSUE TITLE
[Mobile] Responsive UI for Chromebooks - U/X Design

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#489]
### Issue:
Given the prevalence of Chromebooks in the classroom, we'll need to make sure that our `mobile` layouts work across different sized devices.

### Resolution:
Provide U/X design for medium/large layouts.

**Comment by amarax** [comment]
@sincwu a quick first pass of what Chromebook screens may look like can be found at https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12367%3A382145

**Comment by sincwu** [comment]
Awesome first pass, Yong Lin! The way you've structured things is super clear, and that's great that you've already started thinking about not only Chromebooks in landscape view but also iPads/tablets in portrait view (we have had early beta users on all these devices)! As you've surmised, given the prevalence of Chromebooks in schools, our top priority will continue to be on those. Nice work, full speed ahead!

**Comment by amarax** [comment]
First complete draft of responsive guidelines ready for review at https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12367%3A382145. Note that this is likely to require extensive discussion, as they need to be reviewed closely against development constraints.

These guidelines represent types of layouts that will be used by designers. Design components should either specify which standard responsive guideline they are using, OR define their own specific responsive behaviour.

All screens currently in the mobile build have been reviewed and should be able to be constructed using a combination of the responsive layouts.

Examples of previous screens have been shifted to an archive page https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12662%3A390257.

**Comment by amarax** [comment]
@drewjhart @sincwu as we discussed, I've updated the Figma files to also include specific Chromebook screens. You can see the examples:
- `S.1.6` https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12468%3A350932&t=YMrdWuIA82mDAmid-4
- `S.1.9` https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12468%3A351090&t=YMrdWuIA82mDAmid-4

**Comment by amarax** [comment]
Thanks for the review, will now work on translating all the screens over to the responsive guidelines!
