### ISSUE TITLE
Some steps after answer is revealed are right-justified

### ISSUE THREAD

**Issue by zach2025** [rightoneducation/righton-app#492]
![IMG_9114](https://user-images.githubusercontent.com/90917774/208549967-e481616d-24d1-47a1-b2e1-e6fdfd634d00.PNG)
![IMG_9115](https://user-images.githubusercontent.com/90917774/208549970-8c8420e8-21ee-4274-933c-3e83caa71f43.PNG)

**Comment by sincwu** [comment]
Thanks for logging this, Zach! For the person who'll be working on this issue, please make sure all steps are consistently left-aligned -- thanks!
