### ISSUE TITLE
[UX] Update Figma Flow Diagram w/ Side-by-Side Comparison of Mockups vs. Screens Currently in v.0.1

### ISSUE THREAD

**Issue by sincwu** [rightoneducation/righton-app#493]

**Comment by amarax** [comment]
First pass at https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=12488%3A359585&t=JnMz8hrnYfAsq3Rb-4

Questions for team:
- Is the map convention useful for developers as well?
- Is it still useful to have the map format for the screenshot comparison, or is it better to just have screens next to each other in a compact view?

Future improvements:
- Update screenshots with latest build
- Clean up designs to be properly using components
- Discuss automation of screen capture

**Comment by sincwu** [comment]
Wow, Yong Lin, this looks great! 

Hey @Alexandra-Kushnirsky @josephinaim @zach2025 (and no rush, Zach, esp. while you're under the weather this week; hope you feel better soon): Whenever you might be working on UI-related items, please be sure to reference this page in Figma and share your feedback regarding Yong Lin's questions above: what would be most helpful to you?

**Comment by sincwu** [comment]
Hey @amarax, We discussed this at today's dev team meeting, and everyone agreed: if it's not too time-consuming for you, it'd be great to go with the map / flow chart convention.

**Comment by amarax** [comment]
Great, I'll keep the flow chart convention then. I also personally find it useful!

**Comment by sincwu** [comment]
Cool, thanks again!
