### ISSUE TITLE
[Mobile] Update display of correct answer to follow U/X design (S.1.7, S.1.8, S.1.9)

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#511]
### Issue:
This issue occurs based on: https://github.com/rightoneducation/righton-app/issues/462

Yong Lin has updated the Figma for the way we are displaying the correct answer in screens that occur after` CHOOSE_CORRECT_ANSWER`. You can find the U/X design here:
https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=7557%3A221842&t=99u72Dx4zzD7q5rB-0

and it applies to S.1.7, S.1.8, S.1.9. 

### Resolution:
We're just looking to match the U/X design. I think teachers had an issue with the greying out of the button, because they didn't want students to forget the correct answer. The change highlights the correct answer in green and maintains that for the rest of the game. Feel free to consult the original PR for more info, as well as the Figma for the actual updates to be performed. 

Just let me know if you have any questions

**Comment by josephinaim** [comment]
The idea is that the circle with the check mark should be used to indicate that the player had previously gotten the answer correct, while the tick mark alone would be that the player didn’t get it. 

Noted by @amarax

**Comment by amarax** [comment]
I've opened #524 to track the status of the design. For now it's fine to leave the tick as it is.
