### ISSUE TITLE
Updated navigation and search bar

### ISSUE THREAD

**Issue by amarax** [rightoneducation/righton-app#552]
Update the navigation bar to have space for a "Help" button to trigger the onboarding flow. At the same time, consider a new position for the search bar that makes more sense.

**Comment by drewjhart** [comment]
Hi Yong Lin, this looks sick - those dropdown menus are awesome. I'll get started on the updates. I think in terms of capacity I'm not sure if I'll be able to finalize the new dropdown menus before our SXSW deadline in a few weeks (largely as I have `mobile` updates to take care of). At the very least though, I can make use of the existing sort by drop down menu and reposition it on the screen and then update it to this new dropdown styling following the deadline. Let me know if this works for you or you have another suggestion though.

**Comment by amarax** [comment]
That's perfect, the styling alone should get it much closer to being functional and looking good. I'll clean up the Figma file and create a prototype so that it's clear what exact behaviour is expected. 

I accept that not all of the new behaviour will be implemented; do what you can and we can review it from there!

**Comment by amarax** [comment]
@drewjhart I've added a simple prototype to explain how the Search and Sort should work. https://www.figma.com/proto/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?page-id=12122%3A380134&node-id=11952%3A372095&viewport=2438%2C2832%2C0.4&scaling=min-zoom&starting-point-node-id=11952%3A372095&show-proto-sidebar=1

**Comment by drewjhart** [comment]
Awesome, thanks. I'll get started on this and update you as I go.

**Comment by drewjhart** [comment]
Hi Yong Lin,
I've created a PR to address some of the changes above. You can find a complete run down here: https://github.com/rightoneducation/righton-app/pull/555
