### ISSUE TITLE
[Play] - Image Assets in SVG

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#587]
Requesting SVG image assets for:

![Image](https://user-images.githubusercontent.com/79417944/232587135-efd72f11-a15b-496d-ae60-16c536739454.png)

That can handle small/medium/large devices

**Comment by drewjhart** [comment]
Hi @amarax, to add to this: 
I'm also exporting the full sized monster images for use here:
![Image](https://user-images.githubusercontent.com/79417944/232635024-468eb11b-9520-4130-bd0b-c4fa711aa25a.png)

I don't think the original asset export included the shadow for each of the monsters so I created one that scaled the shadows per monster (original on left, new on right):
![Image](https://user-images.githubusercontent.com/79417944/232635266-7707d19f-ed3b-4aaf-a04d-fc807a5da0e6.png)

I did this pretty rushed though and so the monsters aren't aligned to one another (their feet don't occupy the same Y position in the image). So when you click through all the images the monsters seem to jump around. Could I get your Figma expertise to get a set of more consistent monster images with the shadow?

I figure it will look nicer to include a unique, scaled shadow per monster instead of a generic one. Let me know your thoughts though.

**Comment by drewjhart** [comment]
One more @amarax, could I get updated screenshots here:
![Image](https://user-images.githubusercontent.com/79417944/232925474-43aeb8cd-a681-4d94-a92e-664ab2661d91.png)

Like you've done here? 


![Image](https://user-images.githubusercontent.com/79417944/232925544-d4133e86-63cc-40c2-b04c-b59af20a3c9a.png)


I only need the "screenshot" (the half phone image). I was able to pull the monsters and the phase icon just fine off Figma. I'll review this at the meeting today.

**Comment by amarax** [comment]
@drewjhart 

**Onboarding images**: see if this one works https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=13957-164620&t=64IwMoPIgbi65NK2-4

**Monster images**: I've resized the frames to be exactly the same, so if you do proportional scaling the monsters should preserve their relative sizes https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=13957-171311&t=64IwMoPIgbi65NK2-4

**Hero image**: https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=13897-162146&t=64IwMoPIgbi65NK2-4 is my first attempt, but I'll need it to either scale properly (work on your side) or I need to fill in the top of the image (work on my side). Let me figure this one out a bit more first. You can see how it's not really working over [here](https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=13897-162269&t=64IwMoPIgbi65NK2-4).

**Comment by drewjhart** [comment]
Thanks for the above! Whenever you have the chance, would you also be able to do the same for these images?
![image](https://user-images.githubusercontent.com/79417944/236074120-0dc18a75-bd8d-488a-b26a-42819f6a08e3.png)

**Comment by amarax** [comment]
@drewjhart I've managed to compile the assets for the Congratulations screen https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?node-id=14011-164658&t=CWjVGWkk6tOkwdWM-4
