### ISSUE TITLE
When user clicks on a game card to view game details, the title of that game card should be highlighted and visible in the left pane w/o scrolling

### ISSUE THREAD

**Issue by ryanabooth** [rightoneducation/righton-app#65]
In both "Last Updated" and "Alphabetical" views: When user clicks on a game card to view game details, the title of that game card should be highlighted and visible in the left pane w/o scrolling (ideally in the top / upper left of the left pane).

**Comment by sincwu** [comment]
This is a P3 -- not a biggie given that most initial users will be admins who can be given a heads-up / trained on this relatively minor issue. We might consider deferring to post-V1.
