### ISSUE TITLE
[Play] Web App name: Right On!

### ISSUE THREAD

**Issue by cindyqquach** [rightoneducation/righton-app#655]
The name of the web app right now is displayed as Right On! on the iPhone Home Screen. This should be changed into RightOn!
<img src="https://github.com/rightoneducation/righton-app/assets/91432784/e054d785-591b-43be-bd9d-adb78739c656" width="100">

**Comment by drewjhart** [comment]
Hi @cindyqquach, I've resolved this via: https://github.com/rightoneducation/righton-app/pull/657. The most recent version of the app will show this behaviour.
