### ISSUE TITLE
[Backend] - ITeamAnswer Adjustment Proposal

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#781]
## Overview ##
We are currently working on developing 'Intermediate Mode', a new game mode that extends a game session from multiple choice questions to open ended questions. This will provide the student with a text editor in which they can input numbers, strings and Katex forumlae to answer questions. You can find the Figma [here](https://www.figma.com/file/PadzU8GqyhFLCjIt7rQkpE/RightOn-Apps?type=design&node-id=15173-148482&mode=design&t=2jGCUIyJjnEm9hm0-4).

We are using [Quill.js](https://quilljs.com/) via [react-quill](https://www.npmjs.com/package/react-quilll) to provide this input field. Currently, we are using it to provide both regular text and Katex input, with Rich Text deferred. You can see the implementation in [this branch](https://github.com/rightoneducation/righton-app/tree/drew-hart--play-int-open-nohtml). I'm holding off on the PR until we get the backend updates added so that I'm not pushing something that stubs the API calls. 

Personally, after reviewing Quill, TipTap and Lexical, I feel that Quill is a 'good-enough-for-now' solution that will allow us to develop the features we need quickly. I'd eventually like to migrate to Lexical when they release 1.0 though because I feel it will work more seamlessly with React. Currently, though, it lacks the support required for us to deploy it quickly. As such, I've written the quill implmentation so that all data received from the quill pad is parsed by us at the component level. This should allow us to drive in terms of the data structure and then, when we do change the editor, we can just adjust those data-in and data-out functions and not have to change the rest of the app.

**_All that being said, the core issue that requires this adjustment is per below:_**

Quill (as well as lexical) provides a custom data object, called a Quill Delta, that it uses to organize input received and displayed in the Quill editor. This is basically just an object with format per [this](https://quilljs.com/docs/delta/). The key point is that because you can have multiple types of input in a single entry on the pad (for example: a string, then a formula, then a string), they are stored as separate key/value pairs in an object. 

I propose that we should capture this key/value handling of answers. This will allow us to maintain the substructure of open answers that we receive. This is useful if we want to just extract a certain type of content from the broader answer. For example, if a student enters:

```
The answer is: x^2 + 2x + 6
```

We can easily find the part of the answer that is tagged with type 'formula' and forward that as the real answer. 

## Proposed Adjustments ##
My proposed adjustment is to the `ITeamAnswer` object. I am proposing this change:

Current:
``` 
ITeamAnswer {
    id: string,
    questionId: number
    isChosen: boolean
    text: string
    createdAt?: string
    updatedAt?: string
    teamMemberAnswersId?: string | null
    isTrickAnswer: boolean
    confidenceLevel: ConfidenceLevel
} 
```

Proposed:
``` 
ITeamAnswer {
    id: string,
    questionId: number
    isChosen: boolean
    answerTexts: string[]
    answerTypes: AnswerType[]
    createdAt?: string
    updatedAt?: string
    teamMemberAnswersId?: string | null
    isTrickAnswer: boolean
    confidenceLevel: ConfidenceLevel
} 

enum AnswerType {
  MULTICHOICE,
  TEXT,
  FORMULA
}
```

I initially wrote this as a single object (something like `answers: { answerText: string, answerTypes: AnswerType}`) but it seemed weird to nest an additional object within the ITeamAnswer object. I feel that have the fields destructured like this reduces the need to continually parse nested levels and identifies that each of these properties is inherent to the ITeamAnswer object, not some subobject. Totally open to your thoughts though.

## Implications ##
This is a breaking change because it moves our core ITeamAnswer `text` field from a string to an array. As such, we'll need to be strategic in terms of when to make this change so that I can come in and adjust the code in the apps to handle this.

**Comment by drewjhart** [comment]
Also, this is probably something else we can talk through at our Friday meeting.

**Comment by maniramezan** [comment]
hmm, interesting, yeah sounds good, lets cover this as well. Curious to know what's the datatype that quill uses to store its data. I personally like `answers: { answerText: string, answerTypes: AnswerType})` approach more as it prevents us keeping two arrays in sync and also gives us the opportunity to scale and change the json as needed. The parsing concern is valid, but that should only happen in networking so the rest of the app, deal with it as a whole typed object

**Comment by drewjhart** [comment]
Yeah, that makes sense to me. I'll update the branch I'm working on to reflect that preference and we can talk about it further on our call on Friday.
