### ISSUE TITLE
[UX] [Mobile] Need to fix the bottom message invisibility on smaller screens

### ISSUE THREAD

**Issue by maniramezan** [rightoneducation/righton-app#79]
<img src="https://user-images.githubusercontent.com/2628592/104989008-83e3e480-59e7-11eb-875e-716aabd6a389.png" width="320" />

**Comment by amarax** [comment]
Video capture on iPhone 12 Mini
https://user-images.githubusercontent.com/1576365/107393074-4fba9a00-6b35-11eb-8943-5c4c17fc1cea.MP4
