### ISSUE TITLE
[Research] - Implications of moving to previous `GameSessionStates`

### ISSUE THREAD

**Issue by drewjhart** [rightoneducation/righton-app#910]
# Issue: General #

## Overview ##
Teachers have proposed that it would be useful for them to navigate backwards in the app over the course of a GameSession. Currently, our app is entirely connected via subscriptions to the GameSession object (And specifically, to the GameSession.State). We can appreciate the fact that teachers might want some means to navigate through the game, independent of driving student game states. 

There have been two possible ideas (to start with):

1. See if it's possible to have just the teachers move backwards in the GameSession
2. Just provide the information that would have been trying to access in another way (like a tab or something)

## Specific Task ##
This is a short task that will be just an investigation into how difficult/breaking it would be to have teachers move independently of students. Shooting from the hip, I think it would break a lot - probably more than it would be worth - but I think it's worth investigating in a more specific way. Totally open to creative workarounds here that we can then bring up with Sinclair. 

Task - investigate and report back (as a comment in this issue) a quick one page summary of your findings. I'd really like to see the specifics of the break and the reasons why. Additionally, I'd appreciate your opinion on the situation generally and anything you can think to come up with as a solution (which might just be 'no, we can't do this but here's something that could be an alternate'). 

## Relevant Code ##

- GameSessionObject - `networking/amplify/backend/api/mobile/schema.graphql`: 
```
type GameSession @model {
  id: ID!
  gameId: Int!
  startTime: AWSDateTime
  phaseOneTime: Int!
  phaseTwoTime: Int!
  teams: [Team] @hasMany
  currentQuestionIndex: Int
  currentState: GameSessionState!
    @index(name: "byState", queryField: "gameSessionByState")
  gameCode: Int! @index(name: "byCode", queryField: "gameSessionByCode")
  isAdvancedMode: Boolean!
  imageUrl: String
  description: String
  title: String
  currentTimer: Int
  questions: [Question] @hasMany(indexName: "byGameSession", fields: ["id"])
}
```

currentState is the field that, when updated, advances both `host` and `play`

- subscription on `play` - `play/src/hooks/useFetchAndSubscribeGameSession.tsx`
```
 const gameSessionSubscription = apiClient.subscribeUpdateGameSession(
          fetchedGame.id,
          (response) => {
            if (!response) {
              setError(`${t('error.connect.subscriptionerror')}`);
              return;
            }
            // Update the gameSession object and trigger the callback
            if (!ignore) setHasRejoined(false);
            setGameSession((prevGame) => ({ ...prevGame, ...response }));
          }
        );
```

**note: this is the real sticking point. Any time the gameSession object is updated (by host or another player), the gameSession changes are received here. This is by design, because we want to maintain a single source of truth throughout the game (the GameSession object). However, if we were to change the currentState, all players would receive that update too**

- subscription on `host` - `host/src/containers/GameSessionContainer.tsx`
```
    let gameSessionSubscription: any | null = null;
    gameSessionSubscription = apiClient.subscribeUpdateGameSession(
      gameSessionId,
      (response) => {
        // only run the gametimer check on instances where the currentState changes (new screens)
        if (gameSession && gameSession.currentState !== response.currentState) {
          checkGameTimer(response);
        }
        setHintsError(false);
        setGameSession({ ...gameSession, ...response });
        setIsConfidenceEnabled(
          response.questions[response.currentQuestionIndex].isConfidenceEnabled,
        );
        setIsShortAnswerEnabled(response.questions[response.currentQuestionIndex].isShortAnswerEnabled);
        setShortAnswerResponses(response.questions[response.currentQuestionIndex].responses);
      },
    );
 ```
 
 Whenever `play` updates the `GameSession` (by adding an answer, confidence level or hint) the `host` app stays in synch

**Comment by Alexandra-Kushnirsky** [comment]
Here is an initial (maybe naive) approach I think could potentially be a workaround to independent teacher navigation:
Approach: Since host has authority over the subscription of currentGameState, keep currentGameState as is as the global marker of the gameState in the game (for play and host) but add an additional field, maybe ‘currentTeacherGameState’ that is independent of ‘currentGameState’ as a means of allowing just the teacher to move back without changing the global game-state

- Add field ‘teacherGameState’ to networking/amplify/backend/api/mobile/schema.graphql

- Make a ‘dummy’ ref to serve as a back button and use it to update the teacherGameState but NOT the currentGameState. 

- Also make a ‘dummy’ ref to serve as a forward button

(the above two items would require additional UI components)

- Wherever we have logic that triggers an update to ‘currentGameSession’ in the code, we also update ‘currentTeacherGameState’ 

- Add additional logic to handle interaction events with additional forward and back buttons, namely:

- Update the new ‘currentTeacherGameState’ field to the previous state when the back button is pressed and 

- Update the new ‘currentTeacherGameState’ field to the next state IF AND ONLY IF the ‘currentGameState’ is not before the next ‘currentTeacherGameState

_Example 1:_ 
- ‘currentTeacherGameState’ = Question 1, phase 1 choose correct answer

- ‘currentGameState’= Question 1, phase 1 choose the correct answer

- Teacher presses forward button

- ‘currentTeacherGameState’ should not move on to the next phase

_Example 2:_ 

- ‘currentTeacherGameState’ = Question 1, phase 1 choose correct answer

- ‘currentGameState’= Question 1, phase 2 choose the correct answer

- Teacher presses forward button

- ‘currentTeacherGameState’ can move on to Question 1, phase 2 choose the correct answer

Another thought: maybe this does not even have to be a backend change, and we can leave ‘currentTeacherGameState’ to be a locally stored field

**Comment by Alexandra-Kushnirsky** [comment]
Places with switch statements or other dependencies on gameSessionState that would need to be updated to incorporate new independent teacher game session state:

**host/src/components/GameInProgressContentSwitch.jsx:**
 ```
isConfidenceEnabled &&
           (currentState === GameSessionState.CHOOSE_CORRECT_ANSWER ||
             currentState === GameSessionState.PHASE_1_DISCUSS) ? <component> : null
```
- Lines 164-166

```
{isShortAnswerEnabled &&
         (currentState === GameSessionState.CHOOSE_CORRECT_ANSWER ||
           currentState === GameSessionState.PHASE_1_DISCUSS) ? <component> : null
```
- Lines 174-176

```
{isHintEnabled &&
          (currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ||
           currentState === GameSessionState.PHASE_2_DISCUSS) ? <component> : null
```
- Lines 186-188

```
{isHintEnabled &&
          (currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ||
           currentState === GameSessionState.PHASE_2_DISCUSS) ? (
           <div
```
- Lines 274-277

**host/src/components/PlayerThinking/PlayerThinking.jsx**
`{ currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ? <component> : <other component>`
- Line 36 

**host/src/containers/GameSessionContainer.tsx**
```
if (gameSession?.currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER) {
           setHints(rebuildHints(response));
       }
       if (gameSession?.currentState === GameSessionState.PHASE_2_DISCUSS) {
         setGptHints(response.questions[response.currentQuestionIndex].hints);
       }
```
- Lines 118-123 (teacher refresh)

```
Promise.all(teamDataRequests)
       .then((responses) => {
         // if shortAnswer is enabled we need to rebuild the shortAnswerResponses object on refresh
         if (response.questions[response.currentQuestionIndex].isShortAnswerEnabled === true) {
           responses.forEach((team) => {
             team.teamMembers && team.teamMembers.forEach((teamMember) => {
               teamMember.answers && teamMember.answers.forEach((answer) => {
                 if (answer.questionId === response.questions[response.currentQuestionIndex].id
                   && ((response.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER || response.currentState === GameSessionState.PHASE_1_DISCUSS)
                   && answer.isChosen)
                 ) {
                   setShortAnswerResponses((prev) => {
                    return buildShortAnswerResponses(prev, getQuestionChoices(response.questions, response.currentQuestionIndex), response.questions[response.currentQuestionIndex].answerSettings, answer, team.name)
                  });
                 }
               });
             });
           });
         }
         setTeamsArray(responses);
       })
       .catch((reason) => console.log(reason));
   });
```

- Lines 137-159

```
if (gameSession.questions[gameSession.currentQuestionIndex].isShortAnswerEnabled && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER) {
             // we are nesting the short answer response in here because we need to use the teamName and teamId to build the shortAnswerResponses object
             // if we did this outside of the setTeamsArray function we would be using stale state values
```

- Lines 233-235

_All inside handleUpdateGameSession:_
```
if (
     (isShortAnswerEnabled
     || isConfidenceEnabled)
     && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
   )
```

- Lines 371-375

```
if (
     (isShortAnswerEnabled
     || isConfidenceEnabled)
     && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
   )
```

- Lines 391-394

```
if (gameSession.currentState === GameSessionState.PHASE_2_DISCUSS
     && isHintEnabled)
```

- Lines 400-401

```
if (response.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER) {
     setHeaderGameCurrentTime(response.phaseOneTime);
   } else if (
     response.currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER
   )
```

- Lines 407-411

_Inside checkGameTimer_:
```
if (
     gameSession.currentState !== GameSessionState.CHOOSE_CORRECT_ANSWER &&
     gameSession.currentState !== GameSessionState.CHOOSE_TRICKIEST_ANSWER
   )
```

-Lines 418-421

_Inside handleBeginQuestion:_
```
if (gameSession.currentState !== GameSessionState.TEAMS_JOINING)
     return;
   apiClient
     .updateQuestion({
       gameSessionId: gameSessionId,
       id: questionId,
       order: order,
       isConfidenceEnabled: isConfidenceEnabled,
       isShortAnswerEnabled: isShortAnswerEnabled
     })
     .then((response) => {
       let newUpdates = {
         currentState: GameSessionState.CHOOSE_CORRECT_ANSWER,
       };
```

- Lines 444-457

- `Switch statement of gameSession.currentState that renders and returns components on lines 521-620`

**host/src/pages/GameInProgress.jsx**
```
totalRoundTime={
           currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
             ? phaseOneTime
             : phaseTwoTime
         }
```

- Lines 252-256

**host/src/pages/StudentViews.jsx**
```
// determines which student view image to show
 const studentViewImage = (currentState) => {
   if (currentState === GameSessionState.PHASE_1_RESULTS) {
     return SVP1Results;
   } else if (currentState === GameSessionState.PHASE_2_RESULTS) {
     return SVP2Results;
   } else return SVP2Start;
 };
```

- Lines 57-64

```
// determines next state for use by footer
 const nextStateFunc = (currentState) => {
   if (currentState === GameSessionState.PHASE_2_RESULTS && !isLastQuestion) {
     return GameSessionState.TEAMS_JOINING;
   } else {
     let currentIndex = Object.keys(GameSessionState).indexOf(currentState);
     return GameSessionState[Object.keys(GameSessionState)[currentIndex + 1]];
   }
 };
```

- Lines 66-74

```
let isLastGameScreen =
   currentQuestionIndex + 1 === (questions ? questions.length : 0) &&
   currentState === GameSessionState.PHASE_2_RESULTS; // if last screen of last question, head to view final results

```

- Lines 76-78

```
const handleFooterOnClick = () => {
   if (!isLastQuestion && currentState === GameSessionState.PHASE_2_RESULTS) {
     // if they are on the last page a\nd need to advance to the next question
     setIsConfidenceEnabled(false);
     assembleNavDictionary(false, isHintEnabled, GameSessionState.TEAMS_JOINING);
     handleUpdateGameSession({
       currentState: nextStateFunc(currentState),
       currentQuestionIndex: currentQuestionIndex + 1,
     });
     return;
   }
   if (currentState === GameSessionState.PHASE_1_RESULTS)
     assembleNavDictionary(false, isHintEnabled, currentState);
   handleUpdateGameSession({ currentState: nextStateFunc(currentState) });
 };
```

- Lines 81-95

```
<HeaderGame
         totalQuestions={questions ? questions.length : 0}
         currentState={currentState}
         currentQuestionIndex={currentQuestionIndex}
         phaseOneTime={phaseOneTime}
         phaseTwoTime={phaseTwoTime}
         statePosition={
           (statePosition =
             Object.keys(GameSessionState).indexOf(currentState))
         }
       />
```

- Lines 110-120

`<img src={studentViewImage(currentState)} alt="Student View" />`

- Line 123

**Comment by drewjhart** [comment]
> Places with switch statements or other dependencies on gameSessionState that would need to be updated to incorporate new independent teacher game session state:
> 
> **host/src/components/GameInProgressContentSwitch.jsx:**
> 
> ```
> isConfidenceEnabled &&
>           (currentState === GameSessionState.CHOOSE_CORRECT_ANSWER ||
>             currentState === GameSessionState.PHASE_1_DISCUSS) ? <component> : null
> ```
> 
> * Lines 164-166
> 
> ```
> {isShortAnswerEnabled &&
>          (currentState === GameSessionState.CHOOSE_CORRECT_ANSWER ||
>            currentState === GameSessionState.PHASE_1_DISCUSS) ? <component> : null
> ```
> 
> * Lines 174-176
> 
> ```
> {isHintEnabled &&
>           (currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ||
>            currentState === GameSessionState.PHASE_2_DISCUSS) ? <component> : null
> ```
> 
> * Lines 186-188
> 
> ```
> {isHintEnabled &&
>           (currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ||
>            currentState === GameSessionState.PHASE_2_DISCUSS) ? (
>            <div
> ```
> 
> * Lines 274-277
> 
> **host/src/components/PlayerThinking/PlayerThinking.jsx** `{ currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER ? <component> : <other component>`
> 
> * Line 36
> 
> **host/src/containers/GameSessionContainer.tsx**
> 
> ```
> if (gameSession?.currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER) {
>            setHints(rebuildHints(response));
>        }
>        if (gameSession?.currentState === GameSessionState.PHASE_2_DISCUSS) {
>          setGptHints(response.questions[response.currentQuestionIndex].hints);
>        }
> ```
> 
> * Lines 118-123 (teacher refresh)
> 
> ```
> Promise.all(teamDataRequests)
>        .then((responses) => {
>          // if shortAnswer is enabled we need to rebuild the shortAnswerResponses object on refresh
>          if (response.questions[response.currentQuestionIndex].isShortAnswerEnabled === true) {
>            responses.forEach((team) => {
>              team.teamMembers && team.teamMembers.forEach((teamMember) => {
>                teamMember.answers && teamMember.answers.forEach((answer) => {
>                  if (answer.questionId === response.questions[response.currentQuestionIndex].id
>                    && ((response.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER || response.currentState === GameSessionState.PHASE_1_DISCUSS)
>                    && answer.isChosen)
>                  ) {
>                    setShortAnswerResponses((prev) => {
>                     return buildShortAnswerResponses(prev, getQuestionChoices(response.questions, response.currentQuestionIndex), response.questions[response.currentQuestionIndex].answerSettings, answer, team.name)
>                   });
>                  }
>                });
>              });
>            });
>          }
>          setTeamsArray(responses);
>        })
>        .catch((reason) => console.log(reason));
>    });
> ```
> 
> * Lines 137-159
> 
> ```
> if (gameSession.questions[gameSession.currentQuestionIndex].isShortAnswerEnabled && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER) {
>              // we are nesting the short answer response in here because we need to use the teamName and teamId to build the shortAnswerResponses object
>              // if we did this outside of the setTeamsArray function we would be using stale state values
> ```
> 
> * Lines 233-235
> 
> _All inside handleUpdateGameSession:_
> 
> ```
> if (
>      (isShortAnswerEnabled
>      || isConfidenceEnabled)
>      && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
>    )
> ```
> 
> * Lines 371-375
> 
> ```
> if (
>      (isShortAnswerEnabled
>      || isConfidenceEnabled)
>      && gameSession.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
>    )
> ```
> 
> * Lines 391-394
> 
> ```
> if (gameSession.currentState === GameSessionState.PHASE_2_DISCUSS
>      && isHintEnabled)
> ```
> 
> * Lines 400-401
> 
> ```
> if (response.currentState === GameSessionState.CHOOSE_CORRECT_ANSWER) {
>      setHeaderGameCurrentTime(response.phaseOneTime);
>    } else if (
>      response.currentState === GameSessionState.CHOOSE_TRICKIEST_ANSWER
>    )
> ```
> 
> * Lines 407-411
> 
> _Inside checkGameTimer_:
> 
> ```
> if (
>      gameSession.currentState !== GameSessionState.CHOOSE_CORRECT_ANSWER &&
>      gameSession.currentState !== GameSessionState.CHOOSE_TRICKIEST_ANSWER
>    )
> ```
> 
> -Lines 418-421
> 
> _Inside handleBeginQuestion:_
> 
> ```
> if (gameSession.currentState !== GameSessionState.TEAMS_JOINING)
>      return;
>    apiClient
>      .updateQuestion({
>        gameSessionId: gameSessionId,
>        id: questionId,
>        order: order,
>        isConfidenceEnabled: isConfidenceEnabled,
>        isShortAnswerEnabled: isShortAnswerEnabled
>      })
>      .then((response) => {
>        let newUpdates = {
>          currentState: GameSessionState.CHOOSE_CORRECT_ANSWER,
>        };
> ```
> 
> * Lines 444-457
> * `Switch statement of gameSession.currentState that renders and returns components on lines 521-620`
> 
> **host/src/pages/GameInProgress.jsx**
> 
> ```
> totalRoundTime={
>            currentState === GameSessionState.CHOOSE_CORRECT_ANSWER
>              ? phaseOneTime
>              : phaseTwoTime
>          }
> ```
> 
> * Lines 252-256
> 
> **host/src/pages/StudentViews.jsx**
> 
> ```
> // determines which student view image to show
>  const studentViewImage = (currentState) => {
>    if (currentState === GameSessionState.PHASE_1_RESULTS) {
>      return SVP1Results;
>    } else if (currentState === GameSessionState.PHASE_2_RESULTS) {
>      return SVP2Results;
>    } else return SVP2Start;
>  };
> ```
> 
> * Lines 57-64
> 
> ```
> // determines next state for use by footer
>  const nextStateFunc = (currentState) => {
>    if (currentState === GameSessionState.PHASE_2_RESULTS && !isLastQuestion) {
>      return GameSessionState.TEAMS_JOINING;
>    } else {
>      let currentIndex = Object.keys(GameSessionState).indexOf(currentState);
>      return GameSessionState[Object.keys(GameSessionState)[currentIndex + 1]];
>    }
>  };
> ```
> 
> * Lines 66-74
> 
> ```
> let isLastGameScreen =
>    currentQuestionIndex + 1 === (questions ? questions.length : 0) &&
>    currentState === GameSessionState.PHASE_2_RESULTS; // if last screen of last question, head to view final results
> ```
> 
> * Lines 76-78
> 
> ```
> const handleFooterOnClick = () => {
>    if (!isLastQuestion && currentState === GameSessionState.PHASE_2_RESULTS) {
>      // if they are on the last page a\nd need to advance to the next question
>      setIsConfidenceEnabled(false);
>      assembleNavDictionary(false, isHintEnabled, GameSessionState.TEAMS_JOINING);
>      handleUpdateGameSession({
>        currentState: nextStateFunc(currentState),
>        currentQuestionIndex: currentQuestionIndex + 1,
>      });
>      return;
>    }
>    if (currentState === GameSessionState.PHASE_1_RESULTS)
>      assembleNavDictionary(false, isHintEnabled, currentState);
>    handleUpdateGameSession({ currentState: nextStateFunc(currentState) });
>  };
> ```
> 
> * Lines 81-95
> 
> ```
> <HeaderGame
>          totalQuestions={questions ? questions.length : 0}
>          currentState={currentState}
>          currentQuestionIndex={currentQuestionIndex}
>          phaseOneTime={phaseOneTime}
>          phaseTwoTime={phaseTwoTime}
>          statePosition={
>            (statePosition =
>              Object.keys(GameSessionState).indexOf(currentState))
>          }
>        />
> ```
> 
> * Lines 110-120
> 
> `<img src={studentViewImage(currentState)} alt="Student View" />`
> 
> * Line 123

So thorough! Really appreciate you going through this - even if it's a grim task. That should be enough for this issue for sure.

**Comment by Alexandra-Kushnirsky** [comment]
No worries at all, thank you for your guidance on this one!
